version: '3.8'

services:
  sistema-riego:
    build: .
    container_name: sistema-riego-bogota
    environment:
      - API_KEY_CLIMA=${API_KEY_CLIMA}
    restart: unless-stopped
    volumes:
      - ./app:/app
